# Generated by Django 5.0.3 on 2024-03-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcdonalds', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='amount',
        ),
        migrations.AddField(
            model_name='productorder',
            name='_amount',
            field=models.IntegerField(default=1),
        ),
    ]
